# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 226c8b382119f15d10cec70cae2f08990f504883e21716e1a14c0cc981f981b8771cc35ea8444a9abd6bb0af67499eec63bc2f2f01c096274617af9e531c20fa

test:
  secret_key_base: 248a1d452c5d088acb4d3d3cd85fd3f255e5d3f0b4d90b4b0b67251108b86a86e456b93ac5388e96fa1864b0d776156e43a0f390dacf8dabf87b7e782a4b5e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
